fix expiry not working due to kill validation
it raises an error now:

SuperdeskApiError: Can't Kill as article is still available in production

avoid validation callbacks when removing expired articles.