[SDESK-7441] Fixes required for planning tests to run/pass (#2758)
* Fix "AttributeError: 'function' object has no attribute 'reset'" error

SDESK-7441

* Remove "basic" word from token and ascii encoding

The token is taken as it comes from the request headers (without decoding) in the `SuperdeskTokenAuth` class so I'm not sure what was the reason of this encoding + the basic word. Removing this would allow the authentication work in the behave tests

SDESK-7441

* Run steps async until complete

SDESK-7441

* Properly create basic token header

This uses `werkzeug.datastructures.Authorization` to generate a proper basic token auth so we don't need to know the internal details of quart/werkzeug implementation.

SDESK-7441

* Fix typo

SDESK-7441

* Skip sending signals in test env until async is supported

SDESK-7441

* Minor fixes

SDESK-7441